---
configs_dir: "configs/{{ group_names[0] }}/{{ inventory_hostname }}"
complete_configs: "configs/{{ group_names[0] }}/{{ inventory_hostname }}.cfg"

transport: cli

cli:
 host: "{{ ansible_ssh_host }}"
 username: "{{ username }}"
 password: "{{ password }}"
 transport: "{{ transport }}"
 timeout: 600

domain_name: sinog.si

dns_servers: [ 192.168.10.10, 192.168.10.100 ]

dns_server1: 192.168.10.10
dns_server2: 192.168.10.100

ntp_servers: [ 192.168.20.10, 192.168.20.100 ]

syslog_servers: [ 192.168.30.10, 192.168.30.100 ]

tftp_server: 192.168.100.100

banner_exec: banner_exec.txt

snmp_contact: nog@sinog.si
snmp_community: sinog
snmp_group: SINOG
snmp_user: sinog
snmp_auth: sinog1
snmp_priv: sinog2

admins:
 ADMIN: { ipv4: "10.0.1.10", ipv6: "2001:db8:1::10" }

monitoring:
 LIBRENMS: { ipv4: "10.0.1.11", ipv6: "2001:db8:1::11" }

ospf_GLOBAL_id: 1

all_vrfs:
 MGMT: { id: 500 }
 SRV_X: { id: 501 }
