# Path to your oh-my-zsh installation.
  export ZSH=~/oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

plugins=( git ansible zsh-syntax-highlighting )

source $ZSH/oh-my-zsh.sh

# User configuration

export TERM="xterm-256color"

# Preferred editor for local and remote sessions
 if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
 else
   export EDITOR='mvim'
 fi

# History stuff
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS

PROMPT="%{$fg[green]%}%n% $fg[red]%}%B@%m:%b %{$fg[yellow]%}%1~ %{$fg[blue]%}✗ %{$reset_color%}"
