---
- hosts: sw_smb_l2

  gather_facts: no
  connection: local

  vars_files:
  - secure/ssh_user

  tasks:
  - include: tasks/create_dir_file.yml
    tags: [ config ]

  - include: tasks/banners.yml
    tags: [ deploy ]

  - include: tasks/smb_ssh.yml

  - include: tasks/smb_default.yml
 
  - include: tasks/smb_vlans.yml

  - include: tasks/smb_snmp.yml

  - include: tasks/l2_smb_switch/mgmt_int.yml

  - include: tasks/l2_smb_switch/uplinks.yml

  - include: tasks/l2_smb_switch/trunks.yml

  - include: tasks/l2_smb_switch/access.yml

  - include: tasks/smb_int_desc.yml

  - include: tasks/smb_unused_int.yml

  - include: tasks/complete_l2_config.yml
