---
- hosts: smb
  name: config_smb
  connection: local 
  tasks:
   - name: define provider
     set_fact:
       provider:
         host: "{{ ansible_ssh_host }}"
         username: "{{ username }}"
         password: "{{ password }}"
         timeout: 60

   - name: default_config
     ios_template: 
      provider: "{{ provider }}"
      src: templates/smb_sw.j2

   - name: vlans
     ios_template:
      provider: "{{ provider }}"
      src: templates/smb_sw_vlans.j2

   - name: uplinks
     ios_template:
      provider: "{{ provider }}"
      src: templates/smb_sw_uplinks.j2
     with_items: "{{ uplinks }}"      

   - name: interfaces
     ios_template:
      provider: "{{ provider }}"
      src: templates/smb_sw_int.j2
     with_items: "{{ interfaces }}"
