---
- name: config unused interfaces
  template:
   src: templates/cisco_unused_int.j2
   dest: configs/{{ inventory_hostname }}/unused_int.cfg
  tags: [ config ]

- name: non use interfaces
  ios_config:
   provider: "{{ cli }}"
   src: configs/{{ inventory_hostname }}/unused_int.cfg
  tags: [ deploy ]
