---

- name: config default config
  template:
   src: templates/cisco_default.j2
   dest: "{{ configs_dir}}/default_conf.cfg"
  tags: [ config ]

- name: deploy default config
  ios_config:
   provider: "{{ cli }}"
   src: "{{ configs_dir}}/default_conf.cfg"
  tags: [ deploy ]
