---
- name: config unused interfaces
  template:
   src: templates/cisco_unused_int.j2
   dest: "{{ configs_dir}}/unused_int.cfg"
  tags: [ config ]

- name: deploy unused interfaces:w
  ios_config:
   provider: "{{ cli }}"
   src: "{{ configs_dir}}/unused_int.cfg"
  tags: [ deploy ]
