---
- name: config ssh
  template:
   src: templates/smb_ssh.j2
   dest: "{{ configs_dir }}/ssh_conf.cfg"
  tags: [ config ]

- name: deploy ssh
  ios_config:
   provider: "{{ cli }}"
   match: none
   src: "{{ configs_dir }}/ssh_conf.cfg"
  tags: [ deploy ]
