---
- name: config snmp
  template:
   src: templates/smb_snmp.j2
   dest: "{{ configs_dir }}/snmp.cfg"
  tags: [ config ]

- name: deploy snmp
  ios_config:
   provider: "{{ cli }}"
   match: none
   src: "{{ configs_dir }}/snmp.cfg"
  tags: [ deploy snmp ]
