---
- name: config unused interfaces
  template:
   src: templates/smb_unused_int.j2
   dest: configs/{{ inventory_hostname }}/unused_int.cfg
  tags : [ config ]

- name: deploy unused interfaces
  ios_config:
   provider: "{{ cli }}"
   match: none
   src: configs/{{ inventory_hostname }}/unused_int.cfg
  tags : [ deploy ]
