---
- name: config access
  template:
   src: templates/smb_access.j2
   dest: "{{ configs_dir }}/access_int.cfg"
  tags : [ config ]

- name: deploy access
  ios_config:
   provider: "{{ cli }}"
   match: none
   src: "{{ configs_dir }}/access_int.cfg"
  tags : [ deploy ]
