---
- name: config uplinks
  template:
   src: templates/smb_uplinks.j2
   dest: "{{ configs_dir }}/uplink_int.cfg"
  tags : [ config ]

- name: deploy uplinks
  ios_config:
   provider: "{{ cli }}"
   match: none
   src: "{{ configs_dir }}/uplink_int.cfg"
  tags : [ deploy ]
