---
- name: config access
  template:
   src: templates/cisco_access.j2
   dest: "{{ configs_dir}}/access_int.cfg"
  tags: [ config ]

- name: deploy access
  ios_config:
   provider: "{{ cli }}"
   src: "{{ configs_dir}}/access_int.cfg"
  tags: [ deploy ]
