---
- name: config mgmt
  template:
   src: templates/cisco_int_mgmt.j2
   dest: "{{ configs_dir}}/mgmt_int.cfg"
  tags: [ config ]

- name: deploy mgmt
  ios_config:
   provider: "{{ cli }}"
   src: "{{ configs_dir}}/mgmt_int.cfg"
  tags: [ deploy mgmt ]
