---
- name: config trunks
  template:
   src: templates/cisco_trunks.j2
   dest: "{{ configs_dir}}/trunk_int.cfg"
  tags: [ config ]

- name: deploy trunks
  ios_config:
   provider: "{{ cli }}"
   src: "{{ configs_dir}}/trunk_int.cfg"
  tags: [ deploy ]
