---
- name: "config uplinks"
  template:
   src: templates/cisco_uplinks.j2
   dest: "{{ configs_dir}}/uplink_int.cfg"
  tags: [ config ]

- name: "deploy uplinks"
  ios_config:
   provider: "{{ cli }}"
   src: "{{ configs_dir}}/uplink_int.cfg"
  tags: [ deploy ]
