---
- name: config vlans
  template:
   src: templates/cisco_l2_vlans.j2
   dest: configs/{{ inventory_hostname }}/vlans.cfg
  tags: [ config ]

- name: deploy vlans
  ios_config:
   provider: "{{ cli }}"
   src: configs/{{ inventory_hostname }}/vlans.cfg
  tags: [ deploy ]

